/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MarkovChainOptions {
  initialCapacity?: number
}
export declare class MarkovChain {
  constructor(options?: MarkovChainOptions | undefined | null)
  addText(text: string): void
  generate(startWord: string | undefined | null, length: number): string
  getWordCount(): number
  exportCorpus(): string
  importCorpus(json: string): void
}
