/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class MarkovChain {
  constructor()
  addText(text: string): void
  generate(startWord: string | undefined | null, length: number): string
}
